const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),radar=document.getElementById('radar'),rctx=radar.getContext('2d');
const world={w:2400,h:1800},keys={},mouse={x:640,y:360,down:false},p={x:280,y:1040,r:15,hp:100,armor:20,a:0,camX:0,camY:0,weapon:'pistol',mag:18,reserve:120,reload:0,kills:0,xp:0,level:1,digCooldown:0};
const weapons={pistol:{label:'G17',damage:18,rate:.23,mag:18,speed:760,spread:.025},rifle:{label:'AR-15',damage:23,rate:.11,mag:30,speed:850,spread:.045},sniper:{label:'M24',damage:105,rate:1.0,mag:5,speed:1120,spread:.012},shotgun:{label:'SG-12',damage:11,rate:.65,mag:8,speed:700,spread:.15}};
const cratesDef=[['Common','#b9b8a8','ammo'],['Ammo','#e36b32','ammo'],['Medic','#54cf68','med'],['Armor','#4caeff','armor'],['Rifle','#eeb33e','weapon'],['Sniper','#bd75ed','weapon'],['Grenade','#d96464','grenade']];
const missions=[['Collect 3 crates',false],['Defeat 5 enemies',false],['Take down the boss',false],['Hold extraction line',false]],obs=[],crates=[],enemies=[],shots=[],hostile=[],sparks=[],digCraters=[];
const boss={x:1930,y:450,r:42,hp:520,max:520,cd:0,active:true};let state='menu',cool=0,shake=0,last=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
const profileKey='delta-strike-profile-v1';
const readProfile=()=>{try{const raw=localStorage.getItem(profileKey);if(!raw)return{xp:0,missions:0,level:1};const parsed=JSON.parse(raw);return{xp:parsed.xp||0,missions:parsed.missions||0,level:parsed.level||1};}catch{return{xp:0,missions:0,level:1}}};
const saveProfile=profile=>localStorage.setItem(profileKey,JSON.stringify(profile));
const levelForXp=xp=>Math.floor(xp/500)+1;
function updateProfileUI(){const profile=readProfile();const level=levelForXp(profile.xp);const floor=(level-1)*500;const next=level*500;const progress=((profile.xp-floor)/(next-floor))*100;const levelEl=document.getElementById('profileLevel');const xpEl=document.getElementById('profileXP');const barEl=document.getElementById('profileXPBar');const missionsEl=document.getElementById('profileMissions');if(levelEl)levelEl.textContent=`LV ${level}`;if(xpEl)xpEl.textContent=`${profile.xp-floor} / ${next-floor} XP`;if(barEl)barEl.style.width=`${Math.min(100,Math.max(0,progress))}%`;if(missionsEl)missionsEl.textContent=`${profile.missions} MISSIONS`}
function awardXp(amount,label){const profile=readProfile();profile.xp+=amount;profile.level=levelForXp(profile.xp);saveProfile(profile);updateProfileUI();const toast=document.getElementById('xpToast')||document.createElement('div');toast.id='xpToast';toast.textContent=`+${amount} XP // ${label}`;toast.style.position='fixed';toast.style.right='24px';toast.style.bottom='24px';toast.style.zIndex='9999';toast.style.padding='10px 16px';toast.style.background='rgba(16,31,18,.9)';toast.style.border='1px solid rgba(144,223,115,.9)';toast.style.color='#e7f7da';toast.style.fontSize='12px';toast.style.letterSpacing='1.4px';if(!toast.isConnected)document.body.appendChild(toast);clearTimeout(toast._timer);toast._timer=setTimeout(()=>toast.remove(),1200)}
function addBuilding(x,y,w,h,name){obs.push({type:'building',x,y,w,h,name,doors:[{x:x+w*.46,y:y+h-4,w:38,h:8},{x:x+w-4,y:y+h*.38,w:8,h:38}]})}
function createMap(){obs.length=0;addBuilding(300,350,430,300,'WEST BARRACKS');addBuilding(820,260,570,390,'CENTRAL HQ');addBuilding(1510,300,370,300,'EAST WAREHOUSE');addBuilding(470,1110,350,300,'BUNKER SOUTH');addBuilding(1230,1080,470,290,'LAB HALL');addBuilding(1800,1110,430,330,'EAST OUTPOST');const trees=[[100,240,28],[650,210,25],[1480,180,30],[2070,240,27],[2250,650,30],[2050,900,26],[920,820,30],[200,850,25],[850,1530,29],[1500,1570,31],[2200,1510,28],[430,1580,25]];trees.forEach(t=>obs.push({type:'tree',x:t[0],y:t[1],r:t[2]}));const rocks=[[780,820,22],[1450,790,20],[1930,800,25],[890,980,17],[1580,730,18],[360,900,18],[970,1500,20]];rocks.forEach(t=>obs.push({type:'rock',x:t[0],y:t[1],r:t[2]}));const covers=[[760,760,110,16,.1],[940,760,90,16,-.1],[1410,760,115,16,.05],[1610,750,100,16,-.12],[860,900,100,16,.2],[1530,930,90,16,-.2],[900,1450,120,16,-.1],[1600,1450,100,16,.2]];covers.forEach(([x,y,w,h,a])=>obs.push({type:'cover',x,y,w,h,a}))}
function blocked(x,y,r){return obs.some(o=>{if(o.type==='building'){const nx=clamp(x,o.x,o.x+o.w),ny=clamp(y,o.y,o.y+o.h);return (x-nx)**2+(y-ny)**2<r*r}return (x-o.x)**2+(y-o.y)**2<(r+(o.r||0))**2})}
function place(){crates.length=0;for(let i=0;i<30;i++){let x=rand(80,2320),y=rand(80,1720),n=0;while(blocked(x,y,17)&&n++<50){x=rand(80,2320);y=rand(80,1720)}const d=cratesDef[i%cratesDef.length];crates.push({x,y,name:d[0],color:d[1],loot:d[2],open:false})}}
function reset(){p.x=280;p.y=1040;p.hp=100;p.armor=20;p.weapon='pistol';p.mag=18;p.reserve=120;p.reload=0;p.kills=0;p.digCooldown=0;p.xp=readProfile().xp;p.level=levelForXp(p.xp);boss.hp=boss.max;boss.active=true;shots.length=0;hostile.length=0;sparks.length=0;digCraters.length=0;enemies.length=0;for(let i=0;i<12;i++){const ang=Math.random()*Math.PI*2;const rad=60+Math.random()*90;const x=clamp(500+Math.cos(ang)*rad,120,2100);const y=clamp(500+Math.sin(ang)*rad,120,1500);enemies.push({x,y,r:16,hp:45,kind:i%2,attack:0})}createMap();place();updateUI();updateProfileUI()}
function updateUI(){const hpValue=document.getElementById('hpValue'),armorValue=document.getElementById('armorValue'),killValue=document.getElementById('killValue'),ammoValue=document.getElementById('ammoValue'),weaponLabel=document.getElementById('weaponLabel'),healthBar=document.getElementById('healthBar');if(hpValue)hpValue.textContent=Math.ceil(p.hp);if(armorValue)armorValue.textContent=Math.ceil(p.armor);if(killValue)killValue.textContent=p.kills;if(ammoValue)ammoValue.textContent=`${p.mag}/${p.reserve}`;if(weaponLabel)weaponLabel.textContent=weapons[p.weapon].label;if(healthBar)healthBar.style.width=`${clamp((p.hp/100)*100,0,100)}%`}
function reward(name,loot,color){if(loot==='ammo')p.reserve+=30;if(loot==='med')p.hp=clamp(p.hp+25,0,100);if(loot==='armor')p.armor=clamp(p.armor+25,0,100);if(loot==='weapon'){p.weapon=['rifle','sniper','shotgun'][Math.floor(Math.random()*3)];p.mag=weapons[p.weapon].mag;}if(loot==='grenade')p.reserve+=4;triggerLoot(name,loot,color);updateUI()}
function triggerLoot(n,r,c){const crateAnimIcon=document.getElementById('crateAnimIcon'),crateAnimName=document.getElementById('crateAnimName'),crateAnimReward=document.getElementById('crateAnimReward');if(!crateAnimIcon||!crateAnimName||!crateAnimReward)return;crateAnimIcon.style.background=c;crateAnimName.textContent=n;crateAnimReward.textContent=`+ ${r.toUpperCase()}`;const box=document.getElementById('crateAnim');if(box){box.classList.remove('hidden');clearTimeout(triggerLoot.timer);triggerLoot.timer=setTimeout(()=>box.classList.add('hidden'),900)}}
function buildCrates(){const crateList=document.getElementById('crateList');if(!crateList)return;crateList.innerHTML=cratesDef.map(d=>`<div class="crate"><span class="swatch" style="background:${d[1]}"></span><b>${d[0]}</b><small>${d[2]}</small></div>`).join('')}
buildCrates();function fillMissionList(){const missionList=document.getElementById('missionList');if(!missionList)return;missionList.innerHTML=missions.map(([text,done])=>`<li>${done?'✓ ':''}${text}</li>`).join('')}
function openRandomCrate(){const d=cratesDef[Math.floor(Math.random()*cratesDef.length)];reward(d[0],d[2],d[1])}
const startBtn=document.getElementById('startBtn');if(startBtn)startBtn.onclick=()=>{state='play';const startMenu=document.getElementById('startMenu');if(startMenu)startMenu.classList.add('hidden');const profile=readProfile();profile.missions=(profile.missions||0)+1;saveProfile(profile);updateProfileUI();awardXp(50,'DEPLOYMENT');fillMissionList()};const restartBtn=document.getElementById('restartBtn');if(restartBtn)restartBtn.onclick=()=>{const gameOver=document.getElementById('gameOver');if(gameOver)gameOver.classList.add('hidden');const startMenu=document.getElementById('startMenu');if(startMenu)startMenu.classList.remove('hidden');state='menu'};document.getElementById('openRandomBtn').onclick=()=>openRandomCrate();document.querySelectorAll('.weapon').forEach(button=>{button.onclick=()=>{p.weapon=button.dataset.weapon;p.mag=weapons[p.weapon].mag;p.reload=0;updateUI()}});addEventListener('keydown',e=>{const key=e.key.toLowerCase();keys[key]=true;if(key==='r'&&p.mag<weapons[p.weapon].mag&&p.reserve>0)p.reload=.65;if(key==='e'&&p.digCooldown<=0&&state==='play'){p.digCooldown=.35;digAt(p.x,p.y)}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('mousemove',e=>{const rect=canvas.getBoundingClientRect();mouse.x=((e.clientX-rect.left)/rect.width)*canvas.width;mouse.y=((e.clientY-rect.top)/rect.height)*canvas.height});canvas.addEventListener('mousedown',()=>mouse.down=true);canvas.addEventListener('mouseup',()=>mouse.down=false);function fire(){const w=weapons[p.weapon];if(cool>0||p.reload)return;if(!p.mag){p.reload=.65;return}const spreadRange=p.weapon==='shotgun'?[-2,-1,0,1,2]:[0];spreadRange.forEach(i=>{const aa=p.a+i*w.spread;const speed=w.speed;const vx=Math.cos(aa)*speed;const vy=Math.sin(aa)*speed;shots.push({x:p.x+Math.cos(aa)*22,y:p.y+Math.sin(aa)*22,vx,vy,life:1.2,damage:w.damage,from:'player'})});p.mag-=1;cool=w.rate;updateUI()}
function damage(n){if(p.armor){const a=Math.min(p.armor,n*.65);p.armor-=a;n-=a}p.hp-=n;if(p.hp<=0){state='over';const gameOver=document.getElementById('gameOver');if(gameOver){gameOver.classList.remove('hidden');document.getElementById('gameOverText').textContent='Operator eliminated in Sector 07.'}}}
function digAt(x,y){digCraters.push({x,y,r:46,life:3.5});awardXp(8,'TERRAIN DIG');const hits=obs.filter(o=>o.type==='tree'||o.type==='rock'||o.type==='cover');hits.forEach(o=>{if((o.x-x)**2+(o.y-y)**2<(o.r||28)**2+2000){o.x+=(Math.random()-.5)*22;o.y+=(Math.random()-.5)*22}})}
function update(dt){p.digCooldown=Math.max(0,p.digCooldown-dt);cool=Math.max(0,cool-dt);shake=Math.max(0,shake-dt*2);if(state!=='play')return;const dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),len=Math.hypot(dx,dy)||1;const moveX=(dx/len)*220*dt,moveY=(dy/len)*220*dt;const nx=p.x+moveX,constny=p.y+moveY;if(!blocked(nx,p.y,p.r))p.x=nx;if(!blocked(p.x,constny,p.r))p.y=constny;p.x=clamp(p.x,20,world.w-20);p.y=clamp(p.y,20,world.h-20);p.camX=clamp(p.x-640,0,world.w-1280);p.camY=clamp(p.y-360,0,world.h-720);const targetA=Math.atan2(mouse.y-360,mouse.x-640);p.a+=(targetA-p.a)*.2;if(mouse.down)fire();for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.life<=0||s.x<0||s.y<0||s.x>world.w||s.y>world.h){shots.splice(i,1);continue}if(obs.some(o=>o.type==='building'&&s.x>o.x&&s.x<o.x+o.w&&s.y>o.y&&s.y<o.y+o.h)){shots.splice(i,1);continue}enemies.forEach(e=>{if((s.x-e.x)**2+(s.y-e.y)**2<(s.damage*.4+e.r)**2){e.hp-=s.damage;sparks.push({x:s.x,y:s.y,vx:rand(-40,40),vy:rand(-40,40),life:.2,c:'#f7d875'});shots.splice(i,1)}})}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.hp<=0){enemies.splice(i,1);p.kills+=1;awardXp(60,'KILL CONFIRM');if(p.kills>=5)missions[1][1]=true;continue}const dist=Math.hypot(p.x-e.x,p.y-e.y);if(dist<220){const ang=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(ang)*60*dt;e.y+=Math.sin(ang)*60*dt;if(dist<26)damage(10*dt)}}crates.forEach(c=>{c.t=(c.t||0)+dt;if(!c.open&&Math.hypot(p.x-c.x,p.y-c.y)<30){c.open=true;reward(c.name,c.loot,c.color);missions[0][1]=crates.filter(x=>x.open).length>=3;awardXp(25,'CRATE RECOVERY')}});if(boss.active&&Math.hypot(p.x-boss.x,p.y-boss.y)<260){boss.cd-=dt;if(boss.cd<=0){boss.cd=1.2;const ang=Math.atan2(p.y-boss.y,p.x-boss.x);hostile.push({x:boss.x,y:boss.y,vx:Math.cos(ang)*220,vy:Math.sin(ang)*220,life:2.2,from:'boss'})}}hostile.forEach(h=>{h.x+=h.vx*dt;h.y+=h.vy*dt;h.life-=dt;if((h.x-p.x)**2+(h.y-p.y)**2<(h.r||12)**2+200){damage(18);h.life=0}});while(hostile.length&&hostile[0].life<=0)hostile.shift();while(sparks.length&&sparks[0].life<=0)sparks.shift();for(let i=digCraters.length-1;i>=0;i--){digCraters[i].life-=dt;if(digCraters[i].life<=0)digCraters.splice(i,1)}sparks.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});updateUI();fillMissionList()}
function spark(x,y,c,n){for(let i=0;i<n;i++)sparks.push({x,y,vx:rand(-100,100),vy:rand(-100,100),life:rand(.2,.7),c})}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-p.camX,-p.camY);ctx.fillStyle='#7ea05c';ctx.fillRect(0,0,world.w,world.h);for(let y=0;y<world.h;y+=80){for(let x=0;x<world.w;x+=80){ctx.fillStyle=((x+y)%160===0)?'#7d9b50':'#85a75f';ctx.fillRect(x,y,80,80)}}ctx.fillStyle='#9b8b68';ctx.fillRect(0,790,world.w,130);ctx.fillRect(980,0,120,world.h);digCraters.forEach(d=>{ctx.fillStyle='rgba(59,40,33,.75)';ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});obs.forEach(o=>{if(o.type==='building'){ctx.fillStyle='#a9623c';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#573b2c';ctx.lineWidth=8;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#d0b06b';for(let x=o.x+22;x<o.x+o.w-18;x+=40){ctx.fillRect(x,o.y+12,18,16)}}else if(o.type==='tree'){ctx.fillStyle='#315e32';ctx.beginPath();ctx.arc(o.x,o.y,o.r+7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4e8a42';ctx.beginPath();ctx.arc(o.x-5,o.y-7,o.r,0,Math.PI*2);ctx.fill()}else if(o.type==='rock'){ctx.fillStyle='#5c5c59';ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill()}else if(o.type==='cover'){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.a||0);ctx.fillStyle='#5c5140';ctx.fillRect(-o.w/2,-o.h/2,o.w,o.h);ctx.fillStyle='#897453';ctx.fillRect(-o.w/2+3,-o.h/2+3,o.w-6,4);ctx.restore()}});crates.forEach(c=>{if(c.open)return;ctx.fillStyle=c.color;ctx.fillRect(c.x-12,c.y-12,24,24);ctx.strokeStyle='#2c2b2a';ctx.strokeRect(c.x-12,c.y-12,24,24)});enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.atan2(p.y-e.y,p.x-e.x));ctx.fillStyle=e.kind===0?'#3c4850':'#394b39';ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dfe7d9';ctx.fillRect(-8,-13,16,8);ctx.restore()});if(boss.active){ctx.save();ctx.translate(boss.x,boss.y);ctx.fillStyle='#451c1e';ctx.beginPath();ctx.arc(0,0,boss.r+8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#873c32';ctx.beginPath();ctx.arc(0,2,boss.r,0,Math.PI*2);ctx.fill();ctx.restore()}shots.forEach(s=>{ctx.fillStyle='#f7d06f';ctx.fillRect(s.x-2,s.y-2,4,4)});sparks.forEach(s=>{ctx.fillStyle=s.c;ctx.fillRect(s.x,s.y,3,3)});hostile.forEach(h=>{ctx.fillStyle='#d45d5d';ctx.beginPath();ctx.arc(h.x,h.y,8,0,Math.PI*2);ctx.fill()});ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.fillStyle='#d9e8d6';ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#26362e';ctx.fillRect(-8,-14,16,8);ctx.fillStyle='#adbb9f';ctx.fillRect(10,-2,18,4);ctx.restore();ctx.restore();scope();drawRadar()}
function scope(){ctx.fillStyle='rgba(0, 0, 0, 0.35)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(640,360,120,0,Math.PI*2);ctx.fill();ctx.restore();ctx.strokeStyle='rgba(200,230,190,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(640,360,120,0,Math.PI*2);ctx.stroke()}
function drawRadar(){rctx.clearRect(0,0,112,112);rctx.fillStyle='#315b38';rctx.fillRect(0,0,112,112);const sx=112/world.w,sy=112/world.h;obs.filter(o=>o.type==='building').forEach(o=>{rctx.fillStyle='#c5b98c';rctx.fillRect(o.x*sx,o.y*sy,o.w*sx,o.h*sy)});enemies.forEach(e=>{rctx.fillStyle='#e76969';rctx.fillRect(e.x*sx,e.y*sy,5,5)});rctx.fillStyle='#dffae2';rctx.fillRect(p.x*sx,p.y*sy,5,5)}
function loop(t){const dt=Math.min((t-last)/1000||.016,.033);last=t;update(dt);draw();requestAnimationFrame(loop)}
reset();requestAnimationFrame(loop);