const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),radar=document.getElementById('radar').getContext('2d');
const W=3600,H=2400,TILE=60,GRID_W=60,GRID_H=40,keys={},mouse={x:640,y:360,down:false};let state='menu',last=0,fireTimer=0,digTimer=0;
const player={x:360,y:1200,r:16,hp:100,armor:20,angle:0,weapon:'pistol',ammo:18,reserve:120,kills:0};
const guns={pistol:{label:'G17',damage:20,rate:.25,mag:18,speed:780},rifle:{label:'AR-15',damage:24,rate:.1,mag:30,speed:900},sniper:{label:'M24',damage:110,rate:.9,mag:5,speed:1200},shotgun:{label:'SG-12',damage:12,rate:.65,mag:8,speed:700}};
const tiles=Array.from({length:GRID_H},()=>Array.from({length:GRID_W},()=>Math.random()<.11?'rock':'dirt'));
const enemies=[],bullets=[],crates=[],holes=[],decor=[],buildings=[];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b,c,d)=>Math.hypot(a-c,b-d);
function tile(x,y){return{x:Math.floor(x/TILE),y:Math.floor(y/TILE)}}
function createBuildings(){buildings.length=0;[[260,220,260,180],[760,220,280,210],[1320,260,260,200],[1900,260,260,180],[2500,260,300,200],[3100,300,280,190],[460,900,260,200],[1020,930,300,220],[1580,980,260,180],[2150,930,300,220],[2780,1000,280,200],[3220,1050,260,200],[420,1650,260,200],[1080,1580,280,220],[1700,1640,300,200],[2350,1580,280,220],[2920,1650,300,220],[700,2080,280,180],[1420,2050,300,220],[2250,2100,280,190],[3050,2070,300,220]].forEach(([x,y,w,h])=>buildings.push({x,y,w,h,door:{x:x+w/2,y:y+h-5,w:52,h:18}}))}
function inDoor(x,y,b,r=0){const d=b.door;return x+r>d.x-d.w/2&&x-r<d.x+d.w/2&&y+r>d.y-d.h/2&&y-r<d.y+d.h/2}
function blocked(x,y){if(x<0||y<0||x>W||y>H)return true;const t=tile(x,y);if(t.x<0||t.y<0||t.x>=GRID_W||t.y>=GRID_H||tiles[t.y][t.x]==='rock')return true;return buildings.some(b=>x>b.x&&x<b.x+b.w&&y>b.y&&y<b.y+b.h&&!inDoor(x,y,b,16))}
function randomOpen(minDistance=0){let x,y,n=0;do{x=rnd(80,W-80);y=rnd(80,H-80);n++}while((blocked(x,y)||dist(x,y,player.x,player.y)<minDistance)&&n<120);return{x,y}}
function spawn(){enemies.length=0;crates.length=0;holes.length=0;bullets.length=0;buildings.length=0;decor.length=0;createBuildings();Object.assign(player,{x:360,y:1200,hp:100,armor:20,angle:0,kills:0,weapon:'pistol',ammo:18,reserve:120});for(let i=0;i<18;i++){const q=randomOpen(360);enemies.push({x:q.x,y:q.y,r:16,hp:40})}for(let i=0;i<30;i++){const q=randomOpen(180);crates.push({x:q.x,y:q.y,open:false})}for(let i=0;i<180;i++){const q=randomOpen(0);decor.push({x:q.x,y:q.y,type:Math.random()<.5?'bush':'rock'})}}
function ui(){document.getElementById('hpValue').textContent=Math.ceil(player.hp);document.getElementById('armorValue').textContent=Math.ceil(player.armor);document.getElementById('killValue').textContent=player.kills;document.getElementById('ammoValue').textContent=`${player.ammo}/${player.reserve}`;document.getElementById('weaponLabel').textContent=guns[player.weapon].label;document.getElementById('healthBar').style.width=`${clamp(player.hp,0,100)}%`}
function dig(){if(digTimer>0)return;digTimer=.35;const t=tile(player.x,player.y);for(let y=t.y-1;y<=t.y+1;y++)for(let x=t.x-1;x<=t.x+1;x++)if(tiles[y]&&tiles[y][x])tiles[y][x]='dug';holes.push({x:player.x,y:player.y,life:4});if(typeof awardXp==='function')awardXp(8,'TERRAIN DUG')}
function shoot(){const g=guns[player.weapon];if(fireTimer>0||!player.ammo)return;player.ammo--;fireTimer=g.rate;const count=player.weapon==='shotgun'?5:1;for(let i=0;i<count;i++){const a=player.angle+(Math.random()-.5)*(player.weapon==='shotgun'?.18:.025);bullets.push({x:player.x,y:player.y,vx:Math.cos(a)*g.speed,vy:Math.sin(a)*g.speed,damage:g.damage,life:1.5})}}
function hurt(n){const shield=Math.min(player.armor,n*.6);player.armor-=shield;player.hp-=n-shield;if(player.hp<=0){state='over';document.getElementById('gameOver').classList.remove('hidden');document.getElementById('gameOverText').textContent='Operator down in the expanded sector.'}}
function update(dt){fireTimer=Math.max(0,fireTimer-dt);digTimer=Math.max(0,digTimer-dt);if(state!=='play')return;let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),len=Math.hypot(dx,dy)||1,nx=player.x+dx/len*230*dt,ny=player.y+dy/len*230*dt;if(!blocked(nx,player.y))player.x=clamp(nx,16,W-16);if(!blocked(player.x,ny))player.y=clamp(ny,16,H-16);player.angle=Math.atan2(mouse.y-360,mouse.x-640);if(mouse.down)shoot();for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||blocked(b.x,b.y)){bullets.splice(i,1);continue}for(const e of enemies)if(dist(b.x,b.y,e.x,e.y)<e.r+5){e.hp-=b.damage;bullets.splice(i,1);break}}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.hp<=0){enemies.splice(i,1);player.kills++;if(typeof awardXp==='function')awardXp(60,'ENEMY ELIMINATED');continue}const d=dist(player.x,player.y,e.x,e.y);if(d<260){const a=Math.atan2(player.y-e.y,player.x-e.x),ex=e.x+Math.cos(a)*55*dt,ey=e.y+Math.sin(a)*55*dt;if(!blocked(ex,e.y))e.x=ex;if(!blocked(e.x,ey))e.y=ey;if(d<28)hurt(12*dt)}}for(const c of crates)if(!c.open&&dist(player.x,player.y,c.x,c.y)<30){c.open=true;player.reserve+=30;if(typeof awardXp==='function')awardXp(25,'SUPPLY FOUND')}for(let i=holes.length-1;i>=0;i--){holes[i].life-=dt;if(holes[i].life<=0)holes.splice(i,1)}ui()}
function draw(){const camX=clamp(player.x-640,0,W-1280),camY=clamp(player.y-360,0,H-720);ctx.clearRect(0,0,1280,720);ctx.save();ctx.translate(-camX,-camY);for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){ctx.fillStyle=tiles[y][x]==='rock'?'#4d5150':tiles[y][x]==='dug'?'#594638':(x+y)%2?'#769d59':'#81a963';ctx.fillRect(x*TILE,y*TILE,TILE,TILE);ctx.strokeStyle='rgba(0,0,0,.06)';ctx.strokeRect(x*TILE,y*TILE,TILE,TILE)}decor.forEach(o=>{ctx.fillStyle=o.type==='bush'?'#315d35':'#65635a';ctx.beginPath();ctx.arc(o.x,o.y,o.type==='bush'?18:13,0,Math.PI*2);ctx.fill()});holes.forEach(h=>{ctx.fillStyle='rgba(35,24,20,.75)';ctx.beginPath();ctx.arc(h.x,h.y,32,0,Math.PI*2);ctx.fill()});buildings.forEach(b=>{ctx.fillStyle='#403d3b';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#302b28';ctx.fillRect(b.x+10,b.y+10,b.w-20,b.h-20);ctx.strokeStyle='#171817';ctx.lineWidth=8;ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#796c59';ctx.fillRect(b.x+12,b.y+12,b.w-24,6);ctx.fillStyle='#a6c978';ctx.fillRect(b.door.x-b.door.w/2,b.door.y-b.door.h/2,b.door.w,b.door.h);ctx.fillStyle='rgba(180,220,150,.6)';ctx.font='bold 11px sans-serif';ctx.fillText('ENTER',b.door.x-19,b.door.y+4)});crates.forEach(c=>{if(!c.open){ctx.fillStyle='#d49c4d';ctx.fillRect(c.x-11,c.y-11,22,22);ctx.strokeStyle='#372c20';ctx.strokeRect(c.x-11,c.y-11,22,22)}});enemies.forEach(e=>{ctx.fillStyle='#523942';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e8d7be';ctx.fillRect(e.x-7,e.y-13,14,7)});bullets.forEach(b=>{ctx.fillStyle='#ffe07b';ctx.fillRect(b.x-3,b.y-3,6,6)});ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.fillStyle='#d9e8d6';ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#26362e';ctx.fillRect(8,-3,22,6);ctx.restore();ctx.restore();ctx.fillStyle='rgba(0,0,0,.3)';ctx.fillRect(0,0,1280,720);ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(640,360,135,0,Math.PI*2);ctx.fill();ctx.restore();ctx.strokeStyle='rgba(210,240,190,.75)';ctx.beginPath();ctx.arc(640,360,135,0,Math.PI*2);ctx.stroke();radar.clearRect(0,0,112,112);radar.fillStyle='#315b38';radar.fillRect(0,0,112,112);radar.fillStyle='#c3b89b';buildings.forEach(b=>radar.fillRect(b.x/W*112,b.y/H*112,b.w/W*112,b.h/H*112));radar.fillStyle='#e86b6b';enemies.forEach(e=>radar.fillRect(e.x/W*112,e.y/H*112,4,4));radar.fillStyle='#eaffdf';radar.fillRect(player.x/W*112,player.y/H*112,5,5)}
function loop(t){const dt=Math.min((t-last)/1000||.016,.033);last=t;update(dt);draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const key=e.key.toLowerCase();keys[key]=true;if(key==='e')dig();if(key==='r')player.ammo=guns[player.weapon].mag});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*1280/r.width;mouse.y=(e.clientY-r.top)*720/r.height});canvas.addEventListener('mousedown',()=>mouse.down=true);canvas.addEventListener('mouseup',()=>mouse.down=false);document.getElementById('startBtn').onclick=()=>{state='play';document.getElementById('startMenu').classList.add('hidden');if(typeof awardXp==='function')awardXp(50,'DEPLOYMENT')};document.getElementById('restartBtn').onclick=()=>{spawn();state='play';document.getElementById('gameOver').classList.add('hidden')};document.querySelectorAll('.weapon').forEach(b=>b.onclick=()=>{player.weapon=b.dataset.weapon;player.ammo=guns[player.weapon].mag});spawn();ui();requestAnimationFrame(loop);
