/* Gunsmith workbench: weapon selection, attachment slots, and local loadout saving. */
(() => {
  const KEY='delta-strike-loadout-v1';
  const guns={pistol:{name:'G17',class:'SIDEARM',slots:['optic','magazine','grip']},rifle:{name:'AR-15',class:'ASSAULT RIFLE',slots:['optic','barrel','magazine','grip']},sniper:{name:'M24',class:'MARKSMAN RIFLE',slots:['optic','barrel','stock']},shotgun:{name:'SG-12',class:'BREACHER',slots:['muzzle','magazine','grip']}};
  const options={optic:['Red Dot','Holographic','4x Scope'],barrel:['Suppressor','Compensator','Long Barrel'],magazine:['Fast Mag','Extended Mag','Drum Mag'],grip:['Vertical Grip','Angled Grip','Tactical Grip'],stock:['Light Stock','Stability Stock'],muzzle:['Flash Guard','Breacher Choke','Muzzle Brake']};
  let selected='pistol';let loadout=JSON.parse(localStorage.getItem(KEY)||'{}');
  const $=id=>document.getElementById(id);
  function open(){const m=$('gunsmithModal');m.classList.remove('hidden');m.setAttribute('aria-hidden','false');render()}
  function close(){const m=$('gunsmithModal');m.classList.add('hidden');m.setAttribute('aria-hidden','true')}
  function render(){const list=$('gunList');list.innerHTML=Object.entries(guns).map(([id,g])=>`<button class="gun-choice ${id===selected?'active':''}" data-gun="${id}"><b>${g.name}</b><small>${g.class}</small><span>→</span></button>`).join('');list.querySelectorAll('.gun-choice').forEach(b=>b.onclick=()=>{selected=b.dataset.gun;render()});const gun=guns[selected];$('previewName').textContent=gun.name;$('benchStatus').textContent=`${gun.class} // MOD READY`;$('attachmentSlots').innerHTML=gun.slots.map(slot=>`<div class="attachment-slot"><small>${slot.toUpperCase()}</small><b>${loadout[selected]?.[slot]||'EMPTY'}</b></div>`).join('');$('attachmentOptions').innerHTML=gun.slots.map(slot=>`<div class="option-group"><label>${slot.toUpperCase()}</label><div>${options[slot].map(item=>`<button class="attachment-option" data-slot="${slot}" data-item="${item}">${item}</button>`).join('')}</div></div>`).join('');$('attachmentOptions').querySelectorAll('.attachment-option').forEach(b=>b.onclick=()=>{loadout[selected]??={};loadout[selected][b.dataset.slot]=b.dataset.item;render()})}
  document.addEventListener('DOMContentLoaded',()=>{$('openGunsmith')?.addEventListener('click',open);$('closeGunsmith')?.addEventListener('click',close);$('saveLoadout')?.addEventListener('click',()=>{localStorage.setItem(KEY,JSON.stringify(loadout));$('benchStatus').textContent='LOADOUT SAVED // READY';if(typeof awardXp==='function')awardXp(15,'WEAPON MODIFICATION')});addEventListener('keydown',e=>{if(e.key==='Escape')close()});render()});
})();
